import { Experience } from '@/lib/types';

export const experiences: Experience[] = [
  {
    id: '1',
    company: 'RioSaúde - IVISA-Rio',
    companyUrl: 'https://vigilanciasanitaria.prefeitura.rio',
    position: 'Desenvolvedor Full-Stack Pleno',
    period: 'Maio 2024 - Presente',
    startDate: '2024-05',
    current: true,
    location: 'Rio de Janeiro, RJ - Presencial',
    description: [
      'Desenvolvimento, containerização e manutenção de sistemas web em .NET (C#/ASP.NET Core) com front-end em Next.JS/React e aplicações mobile em React Native, atuando em todo o ciclo de vida da aplicação (análise, desenvolvimento, testes e publicação).',
      'Construção de APIs REST e GraphQL para integração entre sistemas internos de saúde, garantindo segurança, performance e padronização das integrações.',
      'Criação e otimização de consultas SQL, procedures e rotinas de banco de dados em SQL Server para suportar grandes volumes de dados da rede de saúde pública.',
      'Participação ativa no levantamento e análise de requisitos junto às áreas de negócio, traduzindo necessidades assistenciais e administrativas em soluções técnicas viáveis.',
      'Colaboração com times multidisciplinares (produto, negócio, infraestrutura) para evoluir funcionalidades críticas para o atendimento à população.',
    ],
    technologies: [
      'C#',
      'ASP.NET Core',
      '.NET',
      'Next.js',
      'React',
      'React Native',
      'Angular',
      'TypeScript',
      'JavaScript',
      'GraphQL',
      'API REST',
      'xUnit',
      'NUnit',
      'SQL',
      'SQL Server',
      'Docker',
      'Kubernetes',
      'Red Hat OpenShift Container Platform (OCP)',
      'Google Cloud Platform (GCP)',
      'Git',
      'GitLab',
    ],
    achievements: [
      'Evolução de sistemas assistenciais com foco em performance e estabilidade em ambiente conteinerizado (Docker e Kubernetes).',
      'Padronização de integrações via APIs REST/GraphQL entre diferentes sistemas internos de saúde.',
      'Desenvolvimento de 3 projetos completos do zero',
      'Mentoria de 3 desenvolvedores júnior',
    ],
  },
  {
    id: '2',
    company: 'RioSaúde - IVISA-Rio',
    companyUrl: 'https://vigilanciasanitaria.prefeitura.rio',
    position: 'Desenvolvedor Full Stack Júnior',
    period: 'Março 2023 - Maio 2024',
    startDate: '2023-03',
    endDate: '2024-05',
    current: false,
    location: 'Rio de Janeiro, RJ - Presencial',
    description: [
      'Atuação no desenvolvimento, containerização e manutenção de sistemas web em .NET (C#/ASP.NET Core) com front-end em React e aplicações mobile em React Native, participando de todo o ciclo de vida da aplicação.',
      'Colaboração na construção de APIs REST e GraphQL para integração entre sistemas internos de saúde, seguindo padrões de segurança e performance definidos pela equipe.',
      'Criação e ajuste de consultas SQL, procedures e rotinas de banco de dados em SQL Server para atender novas demandas de negócio e relatórios.',
      'Apoio no levantamento e análise de requisitos junto às áreas de negócio, contribuindo na tradução de necessidades funcionais em especificações técnicas.',
      'Trabalho em equipe com times multidisciplinares em um ambiente ágil, adotando boas práticas de versionamento, code review e integração contínua.',
    ],
    technologies: [
      'C#',
      'ASP.NET Core',
      '.NET',
      'React',
      'Angular',
      'React Native',
      'TypeScript',
      'JavaScript',
      'GraphQL',
      'API REST',
      'SQL',
      'SQL Server',
      'Docker',
      'Kubernetes',
      'Git',
      'GitLab',
      'xUnit',
      'NUnit',
      'Metodologias Ágeis',
    ],
  },
  {
    id: '3',
    company: 'INEA - Instituto Estadual do Ambiente',
    companyUrl: 'https://www.inea.rj.gov.br',
    position: 'Desenvolvedor Full-Stack .NET - Júnior',
    period: 'Agosto 2022 - Março 2023',
    startDate: '2022-08',
    endDate: '2023-03',
    current: false,
    location: 'Rio de Janeiro, RJ - Presencial',
    description: [
      'Atuação como desenvolvedor full-stack na manutenção e evolução de sistemas ambientais do INEA, incluindo SELCA, Promon Ar, Logística Reversa de Embalagens e ICMS Ecológico.',
      'Desenvolvimento de novas funcionalidades e APIs em ASP.NET Core, integradas a frontends em Angular.',
      'Implementação e ajuste de consultas e rotinas em Oracle e SQL Server para atender novas regras de negócio e relatórios.',
      'Melhoria de telas existentes com foco em usabilidade e desempenho, em alinhamento com as equipes de negócio.',
    ],
    technologies: [
      'ASP.NET Core',
      'C#',
      'Angular',
      'HTML5',
      'CSS3',
      'JavaScript',
      'TypeScript',
      'Oracle Database',
      'SQL Server',
      'Git',
      'IIS',
    ],
    achievements: [
      'Assunção de maior autonomia na entrega de features de ponta a ponta (backend e frontend) em sistemas de licenciamento ambiental.',
      'Apoio na organização do backlog técnico e acompanhamento de demandas via ferramentas de gestão (como Trello/DevOps).',
    ],
  },
  {
    id: '4',
    company: 'INEA - Instituto Estadual do Ambiente',
    companyUrl: 'https://www.inea.rj.gov.br',
    position: 'Desenvolvedor de Software - Estagiário',
    period: 'Janeiro 2022 - Agosto 2022',
    startDate: '2022-01',
    endDate: '2022-08',
    current: false,
    location: 'Rio de Janeiro, RJ - Presencial',
    description: [
      'Atuação no desenvolvimento e manutenção de sistemas de licenciamento e gestão ambiental, como SELCA, Promon Ar, Logística Reversa de Embalagens e ICMS Ecológico.',
      'Desenvolvimento de funcionalidades em aplicações web ASP.NET Core com Angular, além de páginas em HTML e CSS, sempre com orientação de desenvolvedores mais experientes.',
      'Apoio na análise de demandas, correção de bugs e implementação de melhorias em módulos já existentes.',
      'Colaboração com equipes multidisciplinares (analistas, fiscais e gestores) para traduzir regras de negócio ambientais em soluções de software.',
    ],
    technologies: [
      'ASP.NET Core',
      'C#',
      'Angular',
      'HTML5',
      'CSS3',
      'JavaScript',
      'TypeScript',
      'Oracle Database',
      'SQL Server',
      'Git',
      'IIS',
    ],
    achievements: [
      'Participação na evolução de módulos críticos do SELCA, reduzindo retrabalho de análises de processos de licenciamento.',
      'Contribuição para a estabilização de integrações com Oracle e SQL Server, apoiando o desempenho dos sistemas ambientais.',
    ],
  },
];

export const currentExperience = experiences.find(e => e.current);
export const pastExperiences = experiences.filter(e => !e.current);
