import { Project } from '@/lib/types';

export const projects: Project[] = [
  {
    id: '1',
    title: 'SISVISA - Sistema de Vigilância Sanitária (Legado)',
    description: 'Sistema completo de compliance e licenciamento sanitário para o governo do Rio de Janeiro',
    longDescription: 'Plataforma full-stack desenvolvida para gerenciar processos de vigilância sanitária, incluindo licenciamento, fiscalização e documentação de estabelecimentos. Sistema utilizado pela Vigilância Sanitária do Rio de Janeiro (IVISA-Rio) para controle e rastreamento de processos administrativos.',
    technologies: ['C#', 'ASP.NET Core 4.6', 'SQL Server', 'MVC', 'Bootstrap', 'Jenkins', 'GitLab'],
    imageUrl: '/my-page/images/projects/sisvisa-legado.png',
    featured: true,
    category: 'fullstack',
    startDate: '2024-01',
    highlights: [
      'Processamento de mais de 10.000 documentos mensais',
      'Integração com múltiplos sistemas governamentais',
      'Geração dinâmica de documentos PDF',
      'Sistema de workflow para aprovações',
    ],
  },
  {
    id: '2',
    title: 'My-Page',
    description: 'Portfólio pessoal full-stack com Next.js e ASP.NET Core',
    longDescription: 'Portfólio profissional desenvolvido com as tecnologias mais modernas do mercado, demonstrando habilidades em desenvolvimento full-stack, arquitetura de software e boas práticas de programação.',
    technologies: ['Next.js 14', 'React', 'TypeScript', 'Tailwind CSS', 'ASP.NET Core', 'C#'],
    imageUrl: '/my-page/images/projects/mypage.png',
    githubUrl: 'https://github.com/patryckro/my-page',
    liveUrl: 'https://patryckro.github.io/my-page',
    featured: true,
    category: 'fullstack',
    startDate: '2026-02',
  },
  {
    id: '3',
    title: 'App Mobile - Fiscalização Sanitária',
    description: 'Aplicativo mobile para fiscalização em campo com React Native',
    longDescription: 'Aplicativo mobile desenvolvido em React Native para permitir que fiscais sanitários realizem inspeções em campo, com captura de fotos, preenchimento de formulários offline e sincronização automática com o servidor.',
    technologies: ['React Native', 'TypeScript', 'JavaScript', 'SQLite', '.NET', 'ASP.NET Core', 'GraphQL'],
    imageUrl: '/my-page/images/projects/mobile.png',
    featured: true,
    category: 'mobile',
    startDate: '2025-01',
    endDate: '2025-12',
    highlights: [
      'Funcionalidade offline-first',
      'Captura e upload de fotos',
      'Sincronização automática de dados',
      'Geolocalização de inspeções',
      'Interface intuitiva e responsiva',
    ],
  },
  {
    id: '4',
    title: 'SISVISA - Sistema de Vigilância Sanitária (4.0)',
    description: 'Sistema completo de compliance e licenciamento sanitário para o governo do Rio de Janeiro',
    longDescription: 'Plataforma full-stack desenvolvida para gerenciar processos de vigilância sanitária, incluindo licenciamento, fiscalização e documentação de estabelecimentos. Sistema utilizado pela Vigilância Sanitária do Rio de Janeiro (IVISA-Rio) para controle e rastreamento de processos administrativos.',
    technologies: ['.NET 8', 'C#', 'ASP.NET Core', 'SQL Server', 'GraphQL', 'GitLab', 'CI/CD', 'Docker', 'OCP/GCP'],
    imageUrl: '/my-page/images/projects/sisvisa.png',
    featured: true,
    category: 'fullstack',
    startDate: '2025-01',
    highlights: [
      'Processamento de mais de 10.000 documentos mensais',
      'Integração com múltiplos sistemas governamentais',
      'Transcrição automática de áudio para texto',
      'Geração dinâmica de documentos PDF',
      'Sistema de workflow para aprovações',
    ],
  },
  {
    id: '5',
    title: 'SISCURSOS - Sistema de Cursos da Vigilância Sanitária',
    description:  'Sistema interno para gestão de cursos, turmas e certificações da Vigilância Sanitária.',
    longDescription: 'Aplicação web interna utilizada pela Vigilância Sanitária para administrar cursos internos e externos, incluindo gestão de capacitações, turmas, facilitadores (professores), aulas, inscrições, relatórios e emissão de certificados. O sistema centraliza o histórico de participação dos profissionais, apoia o planejamento de treinamentos e garante rastreabilidade das ações de capacitação da área.',
    technologies: [
      'ASP.NET Core',
      'C#',
      '.NET 6',
      'Angular',
      'Angular Material',
      'TypeScript',
      'HTML5',
      'CSS3',
      'Oracle Database',
      'SQL Server',
      'IIS',
      'Git',
      'Visual Studio',
      'VS Code',
    ],
    imageUrl: '/my-page/images/projects/siscursos.png',
    featured: false,
    category: 'fullstack',
    startDate: '2023-03',
    endDate: '2024-05',
     highlights: [
      'Gestão de capacitações, turmas, facilitadores, aulas e participantes em um único sistema.',
      'Emissão de certificados e relatórios para acompanhamento de carga horária e participação em treinamentos.',
    ],
  },
  {
    id: '6',
    title: 'ICMS Ecológico',
    description: 'Sistema para gestão de indicadores e repasse de ICMS Ecológico aos municípios do Rio de Janeiro.',
    longDescription: 'Sistema web responsável pelo cadastro, cálculo e acompanhamento de indicadores ambientais utilizados na composição do ICMS Ecológico, apoiando o repasse de recursos aos municípios com melhor desempenho ambiental. Atuação na manutenção de funcionalidades existentes, correção de bugs e suporte a novas regras de negócio.',
    technologies: [
      'ASP.NET Core',
      'C#',
      '.NET 5',
      'Angular',
      'Angular Material',
      'TypeScript',
      'HTML5',
      'CSS3',
      'Oracle Database',
      'SQL Server',
      'IIS',
      'Git',
      'Visual Studio',
      'VS Code',
    ],
    imageUrl: '/my-page/images/projects/icms-ecologico.png',
    featured: false,
    category: 'fullstack',
    startDate: '2022-01',
    endDate: '2023-03',
    highlights: [
      'Adequação de funcionalidades às mudanças nas regras de cálculo de indicadores.',
      'Apoio à equipe de negócio na validação de dados e resultados de relatórios.',
    ],
  },
  {
    id: '7',
    title: 'Sistema de Logística Reversa de Embalagens',
    description: 'Sistema para registro e acompanhamento de obrigações de logística reversa de embalagens no estado do Rio de Janeiro.',
    longDescription: 'Aplicação web utilizada para controlar cadastros, comprovações e relatórios de logística reversa de embalagens, permitindo que empresas e órgãos ambientais acompanhem o cumprimento das obrigações legais. Atuação na manutenção de telas, regras de negócio e integrações com banco de dados, garantindo aderência às normas ambientais.',
    technologies: [
      'ASP.NET Core',
      'C#',
      'Angular',
      'Angular Material',
      'TypeScript',
      'HTML5',
      'CSS3',
      'Oracle Database',
      'SQL Server',
      'IIS',
      'Git',
      'Visual Studio',
      'VS Code',
    ],
    imageUrl: '/my-page/images/projects/inea.png',
    featured: false,
    category: 'fullstack',
    startDate: '2022-01',
    endDate: '2023-03',
  },
  {
    id: '8',
    title: 'Protocolo Eletrônico - inea',
    description: 'Portal de protocolo eletrônico para envio e acompanhamento digital de documentos e processos junto ao INEA.',
    longDescription: 'Sistema de protocolo eletrônico que permite o envio digital de documentos ao INEA, reduzindo deslocamentos presenciais, agilizando trâmites processuais e permitindo o acompanhamento online por meio de número de protocolo. Integra-se ao SEI-RJ e a fluxos de licenciamento e fiscalização, suportando diferentes tipos de documentos e categorias de atendimento.',
    technologies: [
      'ASP.NET Core',
      'C#',
      'Angular',
      'Angular Material',
      'TypeScript',
      'HTML5',
      'CSS3',
      'Oracle Database',
      'SQL Server',
      'IIS',
      'Git',
      'Visual Studio',
      'VS Code',
    ],
    imageUrl: '/my-page/images/projects/protocolo-eletronico.png',
    featured: false,
    category: 'fullstack',
    startDate: '2022-01',
    endDate: '2023-03',
  },
  {
    id: '9',
    title: 'SELCA - Sistema Estadual de Licenciamento Ambiental',
    description: 'Sistema para gestão de processos de licenciamento ambiental no estado do Rio de Janeiro.',
    longDescription: 'Plataforma web utilizada pelo INEA para cadastro, análise e acompanhamento de processos de licenciamento ambiental, incluindo controle de documentos, prazos, pareceres técnicos e fluxos de aprovação. Atuação na manutenção e evolução de módulos existentes, desenvolvimento de novas funcionalidades e correção de bugs em ambiente de produção.',
    technologies: [
      'ASP.NET Core',
      'C#',
      'Angular',
      'Angular Material',
      'TypeScript',
      'HTML5',
      'CSS3',
      'Oracle Database',
      'SQL Server',
      'IIS',
      'Git',
      'Visual Studio',
      'VS Code',
    ],
    imageUrl: '/my-page/images/projects/selca.png',
    featured: false,
    category: 'fullstack',
    startDate: '2022-01',
    endDate: '2023-03',
    highlights: [
      'Manutenção e evolução de módulos críticos de licenciamento ambiental.',
      'Implementação de ajustes em consultas e rotinas de banco de dados para suportar novos relatórios e regras de negócio.',
    ],
  },
  {
    id: '10',
    title: 'Promon Ar - Programa de Monitoramento de Emissões Atmosféricas',
    description: 'Portal para acompanhamento de emissões atmosféricas de fontes fixas no estado do Rio de Janeiro.',
    longDescription: 'Site institucional do INEA voltado ao Programa de Monitoramento de Emissões Atmosféricas (Promon Ar), com foco na divulgação de informações, relatórios e orientações sobre emissões de fontes fixas. Atuação na manutenção de páginas em HTML e CSS, correção de layout e melhoria de usabilidade.',
    technologies: [
      'ASP.NET Core',
      'C#',
      'Angular',
      'Angular Material',
      'TypeScript',
      'HTML5',
      'CSS3',
      'Oracle Database',
      'SQL Server',
      'IIS',
      'Git',
      'Visual Studio',
      'VS Code',
    ],
    imageUrl: '/my-page/images/projects/inea.png',
    featured: false,
    category: 'fullstack',
    startDate: '2022-01',
    endDate: '2023-03',
  },
];

export const featuredProjects = projects.filter(p => p.featured);

export const projectsByCategory = (category: Project['category']) => 
  projects.filter(p => p.category === category);
